services:
  app:
    build: 
      context: .
    ports:
      - "8501:8501"
    depends_on:
      - ollama
    networks:
      - rede-app
    volumes:
      - ./src:/app
    working_dir:  /app
    command: ["python", "-m", "streamlit", "run", "main.py", "--server.port=8501", "--server.address=0.0.0.0"]
      

  ollama:
    image: ollama/ollama
    ports: 
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    networks:
      - rede-app
    entrypoint: ["sh", "/entrypoint.sh"]

volumes:
  ollama-data:

networks:
  rede-app: