services:
  app:
    build: 
      context: .
    ports:
      - "8501:8501"
    depends_on:
      - ollama
    networks:
      - rede-app
      

  ollama:
    image: ollama/ollama
    ports: 
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    networks:
      - rede-app
    entrypoint: ["sh", "/entrypoint.sh"]

volumes:
  ollama-data:

networks:
  rede-app: